version: "3.9"
services:
  jupyter:
    build: .
    container_name: schema_generator_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root 
        --NotebookApp.token='' 
        --NotebookApp.password='' 
        --NotebookApp.disable_check_xsrf=True
